version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3366:3306'
    expose:
      - '3306'


